// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2r832y-vJ-oWTiDghoxEGVhtY91GiTyY',
    appId: '1:101464372026:web:22553e2049389c2d575603',
    messagingSenderId: '101464372026',
    projectId: 'education-app-77038',
    authDomain: 'education-app-77038.firebaseapp.com',
    storageBucket: 'education-app-77038.appspot.com',
    measurementId: 'G-HSL436C4GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVInpYq2VIK7OiJddF6q_kzk88i7dLedI',
    appId: '1:101464372026:android:ce5826078b365abe575603',
    messagingSenderId: '101464372026',
    projectId: 'education-app-77038',
    storageBucket: 'education-app-77038.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB04k-IAi1VnCVcbYFZy7sowUTWWwttoAU',
    appId: '1:101464372026:ios:c9530f73e6d05428575603',
    messagingSenderId: '101464372026',
    projectId: 'education-app-77038',
    storageBucket: 'education-app-77038.appspot.com',
    iosBundleId: 'com.company.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB04k-IAi1VnCVcbYFZy7sowUTWWwttoAU',
    appId: '1:101464372026:ios:33dcad1399fcd8af575603',
    messagingSenderId: '101464372026',
    projectId: 'education-app-77038',
    storageBucket: 'education-app-77038.appspot.com',
    iosBundleId: 'com.company.educationApp.RunnerTests',
  );
}
